// Optimized HomeScreen (generated by BFF)
// File: frontend/lib/features/home/screens/home_screen.optimized.dart

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:frontend/core/services/api_client_provider.dart';
import 'package:frontend/features/build/providers/build_provider.dart';
import 'package:frontend/features/home/screens/component_detail_screen.dart';
import 'package:frontend/features/home/screens/featured_build_detail_screen.dart';
import 'package:frontend/features/home/widgets/carousel_banner.dart';
import 'package:frontend/features/navigation/providers/nav_provider.dart';
import '/features/home/widgets/auto_build_dialog.dart';
import 'package:frontend/features/cart/screens/cart_screen.dart';

import '../providers/featured_provider.dart';
import '../providers/trending_provider.dart';
import '../providers/auto_build_provider.dart';
import 'autobuild_result_screen.dart';
import '../data/tips_data.dart';
import '../widgets/tips/tip_card.dart';

class HomeScreen extends ConsumerStatefulWidget {
  static const routeName = '/home';
  const HomeScreen({super.key});

  @override
  ConsumerState<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends ConsumerState<HomeScreen> {
  static const String FALLBACK_IMAGE = "assets/banners/autobuild.jpg";
  String? selectedPurpose;

  // Trigger the auto-build using provider, await result, then navigate
  Future<void> _runAutoBuildAndNavigate(
    BuildContext hostContext,
    String purpose,
    double budget,
  ) async {
    final notifier = ref.read(autoBuildProvider.notifier);

    try {
      await notifier.generateAutoBuild(purpose: purpose, budget: budget);

      // Success → switch to Build tab
      ref.read(navIndexProvider.notifier).state = 1;
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        hostContext,
      ).showSnackBar(SnackBar(content: Text("AutoBuild failed: $e")));
    }
  }

  // Small reusable purpose card
  Widget _modernPurposeCard({
    required IconData icon,
    required String label,
    required bool isSelected,
    required List<Color> gradient,
    required VoidCallback onTap,
  }) {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(14),
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          curve: Curves.easeInOut,
          decoration: BoxDecoration(
            gradient: isSelected
                ? LinearGradient(
                    colors: gradient,
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  )
                : null,
            color: isSelected ? null : Colors.white,
            border: Border.all(
              color: isSelected ? Colors.transparent : const Color(0xFFE8EAFC),
              width: 2,
            ),
            borderRadius: BorderRadius.circular(14),
            boxShadow: isSelected
                ? [
                    BoxShadow(
                      color: gradient[0].withOpacity(0.35),
                      blurRadius: 12,
                      offset: const Offset(0, 4),
                    ),
                  ]
                : [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.05),
                      blurRadius: 4,
                      offset: const Offset(0, 2),
                    ),
                  ],
          ),
          child: Stack(
            children: [
              Center(
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      icon,
                      color: isSelected ? Colors.black : Colors.grey[700],
                      size: 20,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      label,
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: isSelected ? Colors.black : Colors.grey[800],
                      ),
                    ),
                  ],
                ),
              ),
              if (isSelected)
                const Positioned(
                  top: 6,
                  right: 6,
                  child: Icon(
                    Icons.check_circle,
                    color: Colors.white,
                    size: 16,
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }

  // Purpose selection dialog. Important: we capture hostContext to avoid using a dialog's
  // deactivated context when navigating or showing snackbars after Navigator.pop.
  void _showPurposeSelectionDialog(BuildContext hostContext) {
    String? tempSelectedPurpose = selectedPurpose;
    double budget = 25000;

    showDialog(
      context: hostContext,
      barrierColor: Colors.black.withOpacity(0.5),
      builder: (dialogContext) => StatefulBuilder(
        builder: (dialogContext, setDialogState) => Dialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(24),
          ),
          elevation: 8,
          backgroundColor: Colors.white,
          child: Container(
            constraints: BoxConstraints(
              maxHeight: MediaQuery.of(dialogContext).size.height * 0.82,
              maxWidth: 480,
            ),
            child: SingleChildScrollView(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.all(12),
                          decoration: BoxDecoration(
                            gradient: const LinearGradient(
                              colors: [
                                Color.fromARGB(255, 75, 59, 24),
                                Color.fromARGB(255, 39, 36, 36),
                              ],
                            ),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: const Icon(
                            Icons.bolt,
                            color: Color.fromARGB(255, 255, 191, 64),
                            size: 24,
                          ),
                        ),
                        const SizedBox(width: 12),
                        const Expanded(
                          child: Text(
                            'Auto Build My PC',
                            style: TextStyle(
                              fontSize: 22,
                              fontWeight: FontWeight.bold,
                              color: Colors.black87,
                            ),
                          ),
                        ),
                        IconButton(
                          onPressed: () => Navigator.of(dialogContext).pop(),
                          icon: Icon(Icons.close, color: Colors.grey[600]),
                        ),
                      ],
                    ),

                    const SizedBox(height: 20),
                    const Text(
                      'Select your primary purpose:',
                      style: TextStyle(
                        fontSize: 15,
                        fontWeight: FontWeight.w600,
                        color: Colors.grey,
                      ),
                    ),
                    const SizedBox(height: 16),

                    GridView.count(
                      crossAxisCount: 2,
                      shrinkWrap: true,
                      crossAxisSpacing: 12,
                      mainAxisSpacing: 12,
                      childAspectRatio: 2.2,
                      physics: const NeverScrollableScrollPhysics(),
                      children: [
                        _modernPurposeCard(
                          icon: Icons.sports_esports,
                          label: 'Gaming',
                          isSelected: tempSelectedPurpose == 'Gaming',
                          gradient: const [
                            Color(0xFF4facfe),
                            Color(0xFF00f2fe),
                          ],
                          onTap: () => setDialogState(
                            () => tempSelectedPurpose = 'Gaming',
                          ),
                        ),
                        _modernPurposeCard(
                          icon: Icons.edit,
                          label: 'Editing',
                          isSelected: tempSelectedPurpose == 'Basic',
                          gradient: const [
                            Color(0xFF4facfe),
                            Color(0xFF00f2fe),
                          ],
                          onTap: () => setDialogState(
                            () => tempSelectedPurpose = 'Basic',
                          ),
                        ),
                        _modernPurposeCard(
                          icon: Icons.code,
                          label: 'Streaming',
                          isSelected: tempSelectedPurpose == 'Streaming',
                          gradient: const [
                            Color(0xFF4facfe),
                            Color(0xFF00f2fe),
                          ],
                          onTap: () => setDialogState(
                            () => tempSelectedPurpose = 'Streaming',
                          ),
                        ),
                        _modernPurposeCard(
                          icon: Icons.work,
                          label: 'Office Work',
                          isSelected: tempSelectedPurpose == 'Workstation',
                          gradient: const [
                            Color(0xFF4facfe),
                            Color(0xFF00f2fe),
                          ],
                          onTap: () => setDialogState(
                            () => tempSelectedPurpose = 'Workstation',
                          ),
                        ),
                      ],
                    ),

                    const SizedBox(height: 20),

                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: const Color(0xFFF8F9FE),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: const Color(0xFFE8EAFC)),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text(
                                'Budget',
                                style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 12,
                                  vertical: 8,
                                ),
                                decoration: BoxDecoration(
                                  gradient: const LinearGradient(
                                    colors: [
                                      Color(0xFF4facfe),
                                      Color(0xFF00f2fe),
                                    ],
                                  ),
                                  borderRadius: BorderRadius.circular(20),
                                ),
                                child: Text(
                                  '₱${_formatPrice(budget.toInt())}',
                                  style: const TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 12),
                          SliderTheme(
                            data: SliderThemeData(
                              activeTrackColor: const Color(0xFF00f2fe),
                              inactiveTrackColor: const Color(0xFFE8EAFC),
                              thumbColor: Colors.white,
                              overlayColor: Colors.black.withOpacity(0.08),
                              trackHeight: 6,
                              thumbShape: const RoundSliderThumbShape(
                                enabledThumbRadius: 12,
                              ),
                            ),
                            child: Slider(
                              value: budget,
                              min: 25000,
                              max: 150000,
                              divisions: 25,
                              label: '₱${budget.toInt()}',
                              onChanged: (v) =>
                                  setDialogState(() => budget = v),
                            ),
                          ),
                          const SizedBox(height: 6),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: const [
                              Text(
                                '₱25,000',
                                style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.grey,
                                ),
                              ),
                              Text(
                                '₱150,000',
                                style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.grey,
                                ),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),

                    const SizedBox(height: 20),

                    SizedBox(
                      width: double.infinity,
                      height: 52,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF4facfe),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                        onPressed: () {
                          if (tempSelectedPurpose == null) {
                            // use dialogContext to show validation (still active)
                            ScaffoldMessenger.of(dialogContext).showSnackBar(
                              const SnackBar(
                                content: Text('Please select a purpose first'),
                              ),
                            );
                            return;
                          }

                          // close dialog first (dialogContext is valid here)
                          Navigator.of(dialogContext).pop();

                          // update parent state safely
                          if (!mounted) return;
                          setState(() => selectedPurpose = tempSelectedPurpose);

                          // trigger autobuild using hostContext (safe for navigation & snackbars)
                          _runAutoBuildAndNavigate(
                            hostContext,
                            tempSelectedPurpose!,
                            budget,
                          );
                        },
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: const [
                            Icon(Icons.rocket_launch, color: Colors.white),
                            SizedBox(width: 10),
                            Text(
                              'Build My PC',
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  String _formatPrice(int price) {
    final s = price.toString();
    return s.replaceAllMapped(
      RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
      (m) => '${m[1]},',
    );
  }

  @override
  Widget build(BuildContext context) {
    final featured = ref.watch(featuredBuildsProvider);
    final trending = ref.watch(trendingComponentsProvider);

    return Scaffold(
      backgroundColor: const Color(0xFF00E5D9).withOpacity(0.04),
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Top bar
              Container(
                height: 68,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                    colors: [Color(0xFF1976D2), Color(0xFF42A5F5)],
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.blue.withOpacity(0.20),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'PC Component Picker',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w700,
                        fontSize: 18,
                      ),
                    ),
                    Row(
                      children: [
                        IconButton(
                          onPressed: () =>
                              Navigator.pushNamed(context, '/search'),
                          icon: const Icon(Icons.search, color: Colors.white),
                        ),
                        IconButton(
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (_) => const CartScreen(),
                              ),
                            );
                          },
                          icon: const Icon(
                            Icons.shopping_cart_outlined,
                            color: Colors.white,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: const CarouselBanner(),
              ),

              const SizedBox(height: 16),

              // Auto Build card
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Material(
                  borderRadius: BorderRadius.circular(12),
                  child: InkWell(
                    borderRadius: BorderRadius.circular(12),
                    onTap: () => AutoBuildDialog.show(context, ref),

                    child: Container(
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Color(0xFFB6F0FF), Color(0xFF66F0D1)],
                        ),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 16,
                      ),
                      child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(
                              color: Colors.white.withOpacity(0.5),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: const Icon(
                              Icons.auto_awesome,
                              color: Colors.white,
                            ),
                          ),
                          const SizedBox(width: 14),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: const [
                                Text(
                                  'Automatic Build',
                                  style: TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                                SizedBox(height: 4),
                                Text(
                                  'Tell us what you need your PC for',
                                  style: TextStyle(
                                    fontSize: 13,
                                    color: Colors.black54,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const Icon(
                            Icons.arrow_forward_ios,
                            color: Colors.black54,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),

              const SizedBox(height: 18),

              // Featured header
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  children: const [
                    Text(
                      'Featured Builds',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    Spacer(),
                  ],
                ),
              ),

              const SizedBox(height: 12),

              // Featured list
              SizedBox(
                height: 260,
                child: featured.when(
                  data: (list) {
                    if (list.isEmpty)
                      return const Center(child: Text('No featured builds'));
                    return ListView.separated(
                      padding: const EdgeInsets.symmetric(horizontal: 16),
                      scrollDirection: Axis.horizontal,
                      itemCount: list.length,
                      separatorBuilder: (_, __) => const SizedBox(width: 12),
                      itemBuilder: (_, i) {
                        final b = list[i];
                        final title = (b['title'] ?? 'Build').toString();
                        final desc = (b['description'] ?? '').toString();
                        final price = b['price'] != null
                            ? '₱${b['price']}'
                            : '₱0';

                        final image = (b['image_url'] ?? FALLBACK_IMAGE)
                            .toString();

                        return _FeaturedCard(
                          imageUrl: image,
                          title: title,
                          subtitle: desc,
                          price: price,
                          onTap: () => Navigator.pushNamed(
                            context,
                            FeaturedBuildDetailScreen.routeName,
                            arguments: b,
                          ),
                        );
                      },
                    );
                  },
                  loading: () =>
                      const Center(child: CircularProgressIndicator()),
                  error: (e, s) =>
                      Center(child: Text('Failed to load featured: $e')),
                ),
              ),

              const SizedBox(height: 18),

              // Trending header
              // Trending header
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  children: const [
                    Text(
                      'Trending Components',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    Spacer(),
                  ],
                ),
              ),

              const SizedBox(height: 12),

              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: trending.when(
                  data: (list) {
                    if (list.isEmpty) return const Text('No trending items');

                    return Column(
                      children: list.map((c) {
                        final name = (c['name'] ?? 'Unknown').toString();
                        final category = (c['category'] ?? 'Component')
                            .toString();

                        final img = (c['image_url'] ?? FALLBACK_IMAGE)
                            .toString();

                        return Padding(
                          padding: const EdgeInsets.symmetric(vertical: 8),
                          child: _TrendingListItem(
                            title: name,
                            subtitle: category,
                            imageUrl: img,

                            onTap: () async {
                              final api = ref.read(apiClientProvider);

                              // Load spinner
                              showDialog(
                                context: context,
                                barrierDismissible: false,
                                builder: (_) => const Center(
                                  child: CircularProgressIndicator(),
                                ),
                              );

                              try {
                                // 🔥 Fetch full component details + specs
                                final full = await api.get(
                                  "/componentspublic/${c['id']}",
                                );

                                if (!mounted) return;

                                Navigator.pop(context); // close loader

                                Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                    builder: (_) => ComponentDetailScreen(
                                      component: full["data"],
                                    ),
                                  ),
                                );
                              } catch (e) {
                                Navigator.pop(context);

                                ScaffoldMessenger.of(context).showSnackBar(
                                  SnackBar(
                                    content: Text("Failed to load details: $e"),
                                  ),
                                );
                              }
                            },
                          ),
                        );
                      }).toList(),
                    );
                  },
                  loading: () => const Padding(
                    padding: EdgeInsets.symmetric(vertical: 24),
                    child: Center(child: CircularProgressIndicator()),
                  ),
                  error: (e, s) =>
                      Center(child: Text('Failed to load trending: $e')),
                ),
              ),

              const SizedBox(height: 26),

              // Tips & Guides
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  children: const [
                    Text(
                      'PC Tips & Guides',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    Spacer(),
                  ],
                ),
              ),

              const SizedBox(height: 12),

              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  children: [
                    for (final tip in tipsData)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 16),
                        child: TipCard(
                          title: tip["title"] as String,
                          description: tip["description"] as String,
                          image: tip["image"] as String,
                          onTap: () {
                            Navigator.pushNamed(
                              context,
                              "/article-detail",
                              arguments: {
                                "title": tip["title"],
                                "image": tip["image"],
                                "content": tip["content"],
                              },
                            );
                          },
                        ),
                      ),
                  ],
                ),
              ),

              const SizedBox(height: 28),
            ],
          ),
        ),
      ),
    );
  }
}

// -------------------- small widget implementations --------------------------

class _FeaturedCard extends StatelessWidget {
  final String imageUrl;
  final String title;
  final String subtitle;
  final String price;
  final VoidCallback? onTap;

  const _FeaturedCard({
    required this.imageUrl,
    required this.title,
    required this.subtitle,
    required this.price,
    this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 200,
      child: GestureDetector(
        onTap: onTap,
        child: Container(
          decoration: BoxDecoration(
            color: const Color(0xFFF7F8FB),
            borderRadius: BorderRadius.circular(14),
            boxShadow: [
              BoxShadow(
                color: Colors.black12,
                blurRadius: 8,
                offset: Offset(0, 4),
              ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              ClipRRect(
                borderRadius: const BorderRadius.vertical(
                  top: Radius.circular(14),
                ),
                child: imageUrl.startsWith('/')
                    ? (File(imageUrl).existsSync()
                          ? Image.file(
                              File(imageUrl),
                              height: 120,
                              width: double.infinity,
                              fit: BoxFit.cover,
                            )
                          : Container(height: 120, color: Colors.grey[300]))
                    : CachedNetworkImage(
                        imageUrl: imageUrl,
                        height: 120,
                        width: double.infinity,
                        fit: BoxFit.cover,
                        placeholder: (_, __) =>
                            Container(height: 120, color: Colors.grey[200]),
                        errorWidget: (_, __, ___) =>
                            Container(height: 120, color: Colors.grey[200]),
                      ),
              ),
              Padding(
                padding: const EdgeInsets.all(12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w700,
                      ),
                      maxLines: 1, // FIX #2
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 6),
                    Text(
                      subtitle,
                      style: const TextStyle(
                        fontSize: 12,
                        color: Colors.black54,
                      ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      price,
                      style: const TextStyle(
                        color: Color(0xFF1976D2),
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 4),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _TrendingListItem extends StatelessWidget {
  final String imageUrl;
  final String title;
  final String subtitle;
  final VoidCallback onTap;

  const _TrendingListItem({
    required this.imageUrl,
    required this.title,
    required this.subtitle,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return Material(
      color: const Color(0xFFF6FBFF),
      borderRadius: BorderRadius.circular(12),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(12),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          decoration: BoxDecoration(
            color: const Color(0xFFF6FBFF),
            borderRadius: BorderRadius.circular(12),
            boxShadow: [
              BoxShadow(
                color: Colors.black12,
                blurRadius: 6,
                offset: Offset(0, 4),
              ),
            ],
          ),
          child: Row(
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(8),
                child: imageUrl.startsWith('/')
                    ? (File(imageUrl).existsSync()
                          ? Image.file(
                              File(imageUrl),
                              height: 56,
                              width: 56,
                              fit: BoxFit.cover,
                            )
                          : Container(
                              width: 56,
                              height: 56,
                              color: Colors.grey[300],
                            ))
                    : CachedNetworkImage(
                        imageUrl: imageUrl,
                        width: 56,
                        height: 56,
                        fit: BoxFit.cover,
                        placeholder: (_, __) => Container(
                          width: 56,
                          height: 56,
                          color: Colors.grey[200],
                        ),
                        errorWidget: (_, __, ___) => Container(
                          width: 56,
                          height: 56,
                          color: Colors.grey[200],
                        ),
                      ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      subtitle,
                      style: const TextStyle(
                        fontSize: 13,
                        color: Colors.black54,
                      ),
                    ),
                  ],
                ),
              ),
              GestureDetector(
                onTap: onTap,
                child: const Text(
                  'View details',
                  style: TextStyle(color: Color(0xFF6B7280)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _InfoCard extends StatelessWidget {
  final String imageUrl;
  final String title;
  final String description;
  final VoidCallback onReadMore;

  const _InfoCard({
    required this.imageUrl,
    required this.title,
    required this.description,
    required this.onReadMore,
  });

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(14),
      child: Container(
        color: const Color(0xFFF3F7FF),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            imageUrl.startsWith('/')
                ? (File(imageUrl).existsSync()
                      ? Image.file(
                          File(imageUrl),
                          width: double.infinity,
                          height: 160,
                          fit: BoxFit.cover,
                        )
                      : Container(height: 160, color: Colors.grey[200]))
                : CachedNetworkImage(
                    imageUrl: imageUrl,
                    width: double.infinity,
                    height: 160,
                    fit: BoxFit.cover,
                    placeholder: (_, __) =>
                        Container(height: 160, color: Colors.grey[200]),
                    errorWidget: (_, __, ___) =>
                        Container(height: 160, color: Colors.grey[200]),
                  ),
            Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: const TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    description,
                    style: const TextStyle(fontSize: 14, color: Colors.black54),
                  ),
                  const SizedBox(height: 12),
                  TextButton(
                    onPressed: onReadMore,
                    child: const Text('Read more'),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
